/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#91f78e",
        "surface-variant": "#d9dde0",
        "primary-dim": "#005578",
        "tertiary": "#006b1b",
        "inverse-surface": "#0b0f10",
        "on-secondary-container": "#005c55",
        "surface-container-low": "#eef1f3",
        "secondary-fixed-dim": "#60e9da",
        "secondary-dim": "#005a53",
        "on-primary-fixed": "#001a28",
        "error-dim": "#9f0519",
        "inverse-on-surface": "#9a9d9f",
        "primary": "#006289",
        "on-primary": "#e8f4ff",
        "tertiary-fixed-dim": "#83e881",
        "secondary-container": "#70f8e8",
        "inverse-primary": "#2dbcfe",
        "on-error": "#ffefee",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#70f8e8",
        "outline": "#747779",
        "primary-fixed-dim": "#02aeef",
        "tertiary-container": "#91f78e",
        "on-primary-fixed-variant": "#003e58",
        "primary-fixed": "#2dbcfe",
        "tertiary-dim": "#005d16",
        "on-surface-variant": "#595c5e",
        "on-background": "#2c2f31",
        "error": "#b31b25",
        "surface-bright": "#f5f7f9",
        "on-tertiary-container": "#005e17",
        "on-tertiary-fixed-variant": "#00691a",
        "on-surface": "#2c2f31",
        "primary-container": "#2dbcfe",
        "on-secondary-fixed-variant": "#00675f",
        "on-tertiary-fixed": "#00480f",
        "secondary": "#00675f",
        "surface-tint": "#006289",
        "on-error-container": "#570008",
        "on-secondary": "#bffff5",
        "surface-container": "#e5e9eb",
        "on-secondary-fixed": "#004842",
        "on-tertiary": "#d1ffc8",
        "surface": "#f5f7f9",
        "surface-container-highest": "#d9dde0",
        "error-container": "#fb5151",
        "background": "#f5f7f9",
        "surface-container-high": "#dfe3e6",
        "outline-variant": "#abadaf",
        "on-primary-container": "#00344b",
        "surface-dim": "#d0d5d8"
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
    },
  },
  plugins: [],
};
